name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 8.x]     # run on two versions of Node

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}      # install the specified version of Node in our CI env
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      run: |
        yarn install
    - name: yarn test
      run: |
        yarn test
      env:
        CI: true      # create-react-app test's env runs in interactive mode, setting CI to true, runs in non-interactive mode.

    - name: yarn build
      run: |
        yarn run build --if-present

    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f
